### ISSUE TITLE
External data inconsistency

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/nwprun#1]
fcens uses external data from a constant file for input eps model while enda takes them from the freshly archived input, they should use both the archived input if possible.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
