### ISSUE TITLE
Go on without analysis should not be always enabled

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/nwprun#7]
Modification introduced in commit  https://github.com/ARPA-SIMC/nwprun/commit/adcaedd9114e79dd9d05e1a6f16d54cb9298e8bc (go on if analysis is not available) should be enablable by the user and not always on (e.g. for fcens).

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.

**Comment by dcesari** [comment]
Potrebbe essere ancora attuale
